name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}
      
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm ci

      - run: npm run build --if-present

      - run: npm test

      - name: Convert Schema to JSON
        run: npm run convert --if-present

      - name: Commit changes
        uses: EndBug/add-and-commit@v8
        with:
          default_author: github_actions
          message: 'Updating schema json files.'
          add: 'resources/user.json'